// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// .env.local (gitignored, per-worktree Neon branch DATABASE_URL from `db:branch`)
// takes priority over .env (from `env:pull`) — first value wins, per dotenv's
// multi-path semantics.
config({ path: [".env.local", ".env"] });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
